Create SECURITY.md file for Pylons GitHub organization
Pylons/.github pull request #1
Opened 2022-03-13 08:21 UTC by stevepiercy

See https://github.com/Pylons/waitress/issues/366

2022-03-14 18:40 UTC, bertjwregeer requested changes

2022-03-14 18:40 UTC, digitalresistor commented on SECURITY.md
> +We volunteers ask that you delay public disclosure of your report for at least seven days from the date you report it to us to allow sufficient time for us to process your report.
I would ask for 90 days by default, and co-ordinated disclosure.

Based upon for example: https://googleprojectzero.blogspot.com/2021/04/policy-and-disclosure-2021-edition.html

2022-03-14 18:40 UTC, digitalresistor commented on SECURITY.md
> +-   report it publically to the MITRE Corporation to its Common Vulnerabilities and Exposures (CVE) List, which in turn submits those to the National Vulnerability Database (NVD),
I've been using the Github Security stuff in Waitress and it has been great. CVE's are obtained from Github after they review the security vulnerability notice. This will also trigger dependabot across the Github ecosystem.

One thing we should add to this list is:

- Provide credit to the reporter/researcher in the vulnerability notice

2022-03-16 05:37 UTC, stevepiercy commented
Thanks @bertjwregeer! Would you please do another review?

2022-03-16 05:37 UTC, stevepiercy commented
Note to self: I should update pylonsproject.org after this PR is approved and merged.

2022-03-17 03:11 UTC, bertjwregeer approved these changes

2022-03-17 03:11 UTC, merged